name: GitHub Classroom Workflow

on:
  schedule:
    - cron: '0 7 2-16 3 *'

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
